/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Establecimiento;

import Conexion.Conexion;
import static Menu.Principal.panelDerecha;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Guada
 */
public class establecimiento extends javax.swing.JPanel {

    /**
     * Creates new form Productor
     */
    int row;

    public establecimiento(){
        initComponents();
//        String cadena = "jdbc:postgresql://localhost:5432/PM-ISI";
//        String user = "postgres";
//        String pass = "boca";

        try {
            Class.forName("org.postgresql.Driver");
            Connection conex = DriverManager.getConnection(Conexion.cadena, Conexion.user, Conexion.pass);
            java.sql.Statement st = conex.createStatement();
            DefaultTableModel m = (DefaultTableModel) tabla.getModel();

            String sql = "SELECT establecimiento.nombre, ubicacion, ecod, productor.nombre as pnombre \n" +
                         "FROM establecimiento, productor \n" +
                         "WHERE establecimiento.pcod = productor.pcod ORDER BY establecimiento.nombre";
            ResultSet result = st.executeQuery(sql);
            String fila[] = new String[4];
            while (result.next()) {
                fila[0] = result.getString("nombre");
                fila[1] = result.getString("ubicacion");
                fila[2] = result.getString("pnombre");
                fila[3] = result.getString("ecod");
                m.addRow(fila);
            }
            tabla.setModel(m);
            result.close();
            st.close();
            conex.close();
        } catch (Exception exc) {
            System.out.println("Errorx:" + exc.getMessage());
        }

        setEventoMouseClicked(tabla);

        //tabla.addMouseListener(new MouseAdapter());
    }

    private void setEventoMouseClicked(JTable tbl) {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tablaMouseClicked(e);
            }
        });
    }

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {
        row = tabla.getSelectedRow();
        if (row != -1){
            borrar.setEnabled(true);
            modificar.setEnabled(true);
            ABM_Animal.setEnabled(true);
            VerDatosEstadisticos.setEnabled(true);
        }else{
            borrar.setEnabled(false);
            modificar.setEnabled(false);
            ABM_Animal.setEnabled(false);
            VerDatosEstadisticos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        tablaEstab = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        ABM_Animal = new javax.swing.JButton();
        VerDatosEstadisticos = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 499));

        borrar.setText("Borrar");
        borrar.setEnabled(false);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.setEnabled(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestión de Establecimiento");

        jTextField1.setText("Nombre...");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ubicación", "Productor (Dueño)", "eCod"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstab.setViewportView(tabla);

        ABM_Animal.setText("ABM Animal");
        ABM_Animal.setEnabled(false);
        ABM_Animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABM_AnimalActionPerformed(evt);
            }
        });

        VerDatosEstadisticos.setText("Ver datos estadisticos");
        VerDatosEstadisticos.setEnabled(false);
        VerDatosEstadisticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosEstadisticosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tablaEstab, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ABM_Animal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VerDatosEstadisticos, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablaEstab, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(borrar)
                        .addGap(31, 31, 31)
                        .addComponent(modificar)
                        .addGap(36, 36, 36)
                        .addComponent(ABM_Animal)
                        .addGap(38, 38, 38)
                        .addComponent(VerDatosEstadisticos))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void ABM_AnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABM_AnimalActionPerformed
        String codEstab = (String) tabla.getValueAt(row,3);//codigo del establecimiento al que pertenece el animal
        Animal panelAnimal = new Animal(codEstab);
        panelAnimal.setSize(1000,599);
        panelAnimal.setLocation(5, 5);
        panelDerecha.removeAll();
        panelDerecha.add(panelAnimal);
        panelDerecha.revalidate();
        panelDerecha.repaint();
        panelAnimal.codigoE = (codEstab);
    }//GEN-LAST:event_ABM_AnimalActionPerformed

    private void VerDatosEstadisticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosEstadisticosActionPerformed
        Dimension d = panelDerecha.getSize();
        
        // Grafico "Produccion de leche por mes"
        //Grafico g = new Grafico();
        //ChartPanel PanelGraf = new ChartPanel(g.grafica);
        //PanelGraf.setSize(100, 100);
        
        //Ventana.getContentPane().add(Panel);
        //Ventana.pack();
        //Ventana.setVisible(true);
        //Ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        Estadisticas Panel = new Estadisticas(Integer.parseInt((String)tabla.getValueAt(row, 3)));
        //ChartPanel Panel = new ChartPanel(nuevo.grafica);
        
        //Panel.setSize(d.width/2, d.height/2);  
        Panel.setSize(d);
        Panel.setLocation(5, 5);
        panelDerecha.removeAll();
        panelDerecha.add(Panel);
        //Panel.add(PanelGraf);
        //panelDerecha.add(PanelGraf);        
        panelDerecha.revalidate();
        panelDerecha.repaint();
    }//GEN-LAST:event_VerDatosEstadisticosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABM_Animal;
    private javax.swing.JButton VerDatosEstadisticos;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modificar;
    public static javax.swing.JTable tabla;
    public static javax.swing.JScrollPane tablaEstab;
    // End of variables declaration//GEN-END:variables
}
