
package Establecimiento;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class Grafico extends javax.swing.JPanel {
    JFreeChart grafica;
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    
    public Grafico(float lts[]) {
        initComponents();
        
        Datos.addValue(lts[0], "Negocio 1", "Enero");
        Datos.addValue(lts[1], "Negocio 1", "Febrero");
        Datos.addValue(lts[2], "Negocio 1", "Marzo");
        Datos.addValue(lts[3], "Negocio 1", "Abril");
        Datos.addValue(lts[4], "Negocio 1", "Mayo");
        Datos.addValue(lts[5], "Negocio 1", "Junio");
        Datos.addValue(lts[6], "Negocio 1", "Julio");
        Datos.addValue(lts[7], "Negocio 1", "Agosto");
        Datos.addValue(lts[8], "Negocio 1", "Septiembre");
        Datos.addValue(lts[9], "Negocio 1", "Octubre");
        Datos.addValue(lts[10], "Negocio 1", "Noviembre");
        Datos.addValue(lts[11], "Negocio 1", "Diciembre");

        grafica = ChartFactory.createBarChart(" ",
                "Mes", "Lts", Datos,
                PlotOrientation.VERTICAL, false, true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
