/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Productor;

import Conexion.Conexion;
import Establecimiento.AltaEstablecimiento;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Guada
 */
public class GestionarProductor extends javax.swing.JPanel {
    int row;

    /**
     * Creates new form Productor
     */
    public GestionarProductor() {
        initComponents();

        try {
            Class.forName("org.postgresql.Driver");
            Connection conex = DriverManager.getConnection(Conexion.cadena, Conexion.user, Conexion.pass);
            java.sql.Statement st = conex.createStatement();
            DefaultTableModel m = (DefaultTableModel) tabla.getModel();

            String sql = "SELECT * FROM productor ORDER BY nombre";
            ResultSet result = st.executeQuery(sql);
            String fila[] = new String[5];
            while (result.next()) {
                fila[0] = result.getString("nombre");
                fila[1] = result.getString("dni");
                fila[2] = result.getString("telefono");
                fila[3] = result.getString("domicilio");
                fila[4] = result.getString("pcod");
                m.addRow(fila);
            }
            tabla.setModel(m);
            result.close();
            st.close();
            conex.close();
        } catch (Exception exc) {
            System.out.println("Errorx:" + exc.getMessage());
        }

        setEventoMouseClicked(tabla);
    }
    
    private void setEventoMouseClicked(JTable tbl) {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tablaMouseClicked(e);
            }
        });
    }

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {
        row = tabla.getSelectedRow();
        if (row != -1){
            borrar.setEnabled(true);
            modificar.setEnabled(true);
            agregarEstablecimiento.setEnabled(true);
        }else{
            borrar.setEnabled(false);
            modificar.setEnabled(false);
            agregarEstablecimiento.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        buscarNombre = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        tablaProd = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        agregarEstablecimiento = new javax.swing.JButton();

        borrar.setText("Borrar");
        borrar.setEnabled(false);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.setEnabled(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestión de Productor");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscarNombre.setColumns(30);
        buscarNombre.setText("Nombre...");
        buscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarNombreMouseClicked(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI", "Telefono", "Domicilio", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setMinimumSize(new java.awt.Dimension(0, 0));
        tablaProd.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        agregarEstablecimiento.setText("Agregar Establecimiento");
        agregarEstablecimiento.setEnabled(false);
        agregarEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEstablecimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tablaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agregarEstablecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(borrar)
                        .addGap(51, 51, 51)
                        .addComponent(modificar)
                        .addGap(48, 48, 48)
                        .addComponent(agregarEstablecimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tablaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        EliminarProductor borrar = new EliminarProductor();
        borrar.setVisible(true);
        borrar.setLocationRelativeTo(this);
        borrar.nombre.setText((String) tabla.getValueAt(row, 0));
        borrar.dni.setText((String) tabla.getValueAt(row, 1));
        borrar.pcodBorrar = Integer.parseInt((String)tabla.getValueAt(row, 4));
    }//GEN-LAST:event_borrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        EditarProductor edit = new EditarProductor();
        edit.setVisible(true);
        edit.setLocationRelativeTo(this);
        edit.campoNombre.setText((String) tabla.getValueAt(row, 0));
        edit.campoDNI.setText((String) tabla.getValueAt(row, 1));
        edit.campoTelefono.setText((String) tabla.getValueAt(row, 2));
        edit.campoDomicilio.setText((String) tabla.getValueAt(row, 3));
        edit.campoPcod.setText((String) tabla.getValueAt(row, 4));

    }//GEN-LAST:event_modificarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        AgregarProductor nueva = new AgregarProductor();
        nueva.setVisible(true);
        nueva.setLocationRelativeTo(this);
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String nbre = (String) buscarNombre.getText();
        TableRowSorter filtro = new TableRowSorter(tabla.getModel());
        this.repaint();
        filtro.setRowFilter(RowFilter.regexFilter(nbre, 0));
        tabla.setRowSorter(filtro);
        
        setEventoMouseClicked(tabla);
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarNombreMouseClicked
        // TODO add your handling code here:
        buscarNombre.setText(null);
    }//GEN-LAST:event_buscarNombreMouseClicked

    private void agregarEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEstablecimientoActionPerformed
        // TODO add your handling code here:
        AltaEstablecimiento nueva = new Establecimiento.AltaEstablecimiento();
        nueva.setVisible(true);
        nueva.setLocationRelativeTo(this);
        nueva.campoPcod.setText((String) tabla.getValueAt(row, 4));
        
        
    }//GEN-LAST:event_agregarEstablecimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregarEstablecimiento;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificar;
    public static javax.swing.JTable tabla;
    public static javax.swing.JScrollPane tablaProd;
    // End of variables declaration//GEN-END:variables
}
