/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Productor;

import Conexion.Conexion;
import Establecimiento.AltaEstablecimiento;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Guada
 */
public class GestionarProductor extends javax.swing.JPanel {
    int row;

    /**
     * Creates new form Productor
     */
    public GestionarProductor() {
        initComponents();

        try {
            Class.forName("org.postgresql.Driver");
            Connection conex = DriverManager.getConnection(Conexion.cadena, Conexion.user, Conexion.pass);
            java.sql.Statement st = conex.createStatement();
            DefaultTableModel m = (DefaultTableModel) tabla.getModel();

            String sql = "SELECT * FROM productor ORDER BY nombre";
            ResultSet result = st.executeQuery(sql);
            String fila[] = new String[5];
            while (result.next()) {
                fila[0] = result.getString("nombre");
                fila[1] = result.getString("dni");
                fila[2] = result.getString("telefono");
                fila[3] = result.getString("domicilio");
                fila[4] = result.getString("pcod");
                m.addRow(fila);
            }
            tabla.setModel(m);
            result.close();
            st.close();
            conex.close();
        } catch (Exception exc) {
            System.out.println("Errorx:" + exc.getMessage());
        }

        setEventoMouseClicked(tabla);
    }
    
    private void setEventoMouseClicked(JTable tbl) {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tablaMouseClicked(e);
            }
        });
    }

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {
        row = tabla.getSelectedRow();
        if (row != -1){
            borrar.setEnabled(true);
            modificar.setEnabled(true);
            agregarEstablecimiento.setEnabled(true);
        }else{
            borrar.setEnabled(false);
            modificar.setEnabled(false);
            agregarEstablecimiento.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        buscarNombre = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        tablaProd = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        agregarEstablecimiento = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        borrar.setText("Borrar");
        borrar.setEnabled(false);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 20, 20);
        add(borrar, gridBagConstraints);

        modificar.setText("Modificar");
        modificar.setEnabled(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(modificar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestión de Productor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jLabel1, gridBagConstraints);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        add(agregar, gridBagConstraints);

        buscarNombre.setColumns(30);
        buscarNombre.setText("Nombre...");
        buscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarNombreMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(buscarNombre, gridBagConstraints);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        add(buscar, gridBagConstraints);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI", "Telefono", "Domicilio", "Codigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setMinimumSize(new java.awt.Dimension(0, 0));
        tablaProd.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tablaProd, gridBagConstraints);

        agregarEstablecimiento.setText("Agregar Establecimiento");
        agregarEstablecimiento.setEnabled(false);
        agregarEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEstablecimientoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(agregarEstablecimiento, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        EliminarProductor borrar = new EliminarProductor();
        borrar.setVisible(true);
        borrar.setLocationRelativeTo(this);
        borrar.nombre.setText((String) tabla.getValueAt(row, 0));
        borrar.dni.setText((String) tabla.getValueAt(row, 1));
        borrar.pcodBorrar = Integer.parseInt((String)tabla.getValueAt(row, 4));
    }//GEN-LAST:event_borrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        EditarProductor edit = new EditarProductor();
        edit.setVisible(true);
        edit.setLocationRelativeTo(this);
        edit.campoNombre.setText((String) tabla.getValueAt(row, 0));
        edit.campoDNI.setText((String) tabla.getValueAt(row, 1));
        edit.campoTelefono.setText((String) tabla.getValueAt(row, 2));
        edit.campoDomicilio.setText((String) tabla.getValueAt(row, 3));
        edit.campoPcod.setText((String) tabla.getValueAt(row, 4));

    }//GEN-LAST:event_modificarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        AgregarProductor nueva = new AgregarProductor();
        nueva.setVisible(true);
        nueva.setLocationRelativeTo(this);
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String nbre = (String) buscarNombre.getText();
        TableRowSorter filtro = new TableRowSorter(tabla.getModel());
        this.repaint();
        filtro.setRowFilter(RowFilter.regexFilter(nbre, 0));
        tabla.setRowSorter(filtro);
        
        setEventoMouseClicked(tabla);
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarNombreMouseClicked
        // TODO add your handling code here:
        buscarNombre.setText(null);
    }//GEN-LAST:event_buscarNombreMouseClicked

    private void agregarEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEstablecimientoActionPerformed
        // TODO add your handling code here:
        AltaEstablecimiento nueva = new Establecimiento.AltaEstablecimiento();
        nueva.setVisible(true);
        nueva.setLocationRelativeTo(this);
        nueva.campoPcod.setText((String) tabla.getValueAt(row, 4));
        
        
    }//GEN-LAST:event_agregarEstablecimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregarEstablecimiento;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton modificar;
    public static javax.swing.JTable tabla;
    public static javax.swing.JScrollPane tablaProd;
    // End of variables declaration//GEN-END:variables
}
